// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxqvrokilktbqlatfhyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4cXZyb2tpbGt0YnFsYXRmaHlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNDI5NzAsImV4cCI6MjA2OTYxODk3MH0.Y3A1qPJZYSyP72Q_wpfn4_OaJ3RTO7dSDAwCCHWX4Lk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});